//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var2Globa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Доп_услуги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Доп_услуги()
        {
            this.Состав_доп_услуги = new HashSet<Состав_доп_услуги>();
        }
    
        public int ID_доп_услуги { get; set; }
        public string Название { get; set; }
        public Nullable<int> Стоимость { get; set; }
        public string Единица { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_доп_услуги> Состав_доп_услуги { get; set; }
    }
}
