//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var2Globa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Состав_доп_услуги = new HashSet<Состав_доп_услуги>();
        }
    
        public int ID_заказа { get; set; }
        public Nullable<int> Клиент { get; set; }
        public Nullable<int> Тип_уборки { get; set; }
        public Nullable<System.DateTime> Дата_исполнения { get; set; }
        public Nullable<int> Исполнитель { get; set; }
        public Nullable<int> Помещение { get; set; }
        public string Статус_заказа { get; set; }
        public string Комментарий { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Клиент Клиент1 { get; set; }
        public virtual Клиент Клиент2 { get; set; }
        public virtual Помещение Помещение1 { get; set; }
        public virtual Тип_уборки Тип_уборки1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_доп_услуги> Состав_доп_услуги { get; set; }
    }
}
