//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var2Globa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Помещение
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Помещение()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int ID_помещение { get; set; }
        public string адрес { get; set; }
        public Nullable<int> Площадь { get; set; }
        public Nullable<int> Тип_помещения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
        public virtual Тип_помещения Тип_помещения1 { get; set; }
    }
}
