//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var2Globa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int ID_сотрудника { get; set; }
        public string ФИО { get; set; }
        public string ИНН { get; set; }
        public string Паспорт { get; set; }
        public string Расчётный_счет { get; set; }
        public Nullable<int> Должность { get; set; }
        public string Логин { get; set; }
        public string Паролб { get; set; }
    
        public virtual Должность Должность1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
