//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var2Globa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_доп_услуги
    {
        public int id_состава { get; set; }
        public Nullable<int> ID_заказа { get; set; }
        public Nullable<int> ID_доп_услуги { get; set; }
    
        public virtual Доп_услуги Доп_услуги { get; set; }
        public virtual Заказ Заказ { get; set; }
    }
}
